# Generated by Django 4.0 on 2021-12-19 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('photo', models.ImageField(default='default-computer.jpg', upload_to='computers/')),
                ('cost', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('publication_year', models.DateField(default=datetime.date(2021, 12, 19))),
                ('computer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.computer')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
            },
        ),
        migrations.DeleteModel(
            name='Donut',
        ),
    ]
