# Generated by Django 4.0 on 2021-12-19 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_computer_operatingsystem_delete_donut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='publication_year',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 10, 16, 48, 975465, tzinfo=utc)),
        ),
    ]
