# Generated by Django 4.0 on 2021-12-19 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_operatingsystem_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='publication_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
