# Generated by Django 4.0 on 2022-01-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('info', models.TextField()),
                ('cost', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='donut-default.jpg', upload_to='donuts/')),
            ],
            options={
                'verbose_name': 'Пончик',
                'verbose_name_plural': 'Пончики',
                'db_table': 'Donuts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DonutsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('info', models.TextField()),
                ('picture', models.ImageField(default='donut-default.jpg', upload_to='donuts/')),
                ('fk_donuts', models.ManyToManyField(to='stocks.Donut')),
            ],
            options={
                'verbose_name': 'Сет пончиков',
                'verbose_name_plural': 'Сеты пончиков',
                'db_table': 'DonutsSets',
                'managed': True,
            },
        ),
    ]
